#ifndef LIBSERVER_H
#define LIBSERVER_H

#define SERVER_IP_ADDR "127.0.0.1"

#define MAJOR_VERSION "1"
#define MINOR_VERSION "0"
#define PATCH_VERSION "6"
#define SERVER_VERSION MAJOR_VERSION"."MINOR_VERSION"."PATCH_VERSION

#define SERVER_DEBUG_PRINTS 0

volatile int keep_running = 1;

enum MENU {
	CHAT = 1,
	RECIEVE_FILE,
	SEND_FILE,
	EXIT
};

#endif // LIBSERVER_H
